apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lndhub.fullname" . }}-config
  labels:
  {{- include "lndhub.labels" . | nindent 4 }}
data:
  config.js: |-
    {{ .Files.Get "config/config.js" | b64enc }}
  admin.macaroon: |-
    {{ .Files.Get "config/admin.macaroon" | b64enc }}
  tls.cert: |-
    {{ .Files.Get "config/tls.cert" | b64enc }}
